version: '3.8'

services:
  opengo_analytics:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opengo_analytics
    environment:
      MONGO_URI: ${MONGO_URI}
      DATABASE_NAME: ${DATABASE_NAME}
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "5000:5000"
    command: streamlit run /app/opengo/pengo_analytics/og_analytics.py
